'use strict';
const vscode=require('vscode');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {CATEGORIES}=require('./data');
const {findAgy,configPath}=require('./system');
async function startJob(categoryId){const c=CATEGORIES.find(x=>x.id===categoryId);if(!c)return;const agy=findAgy();if(!agy){vscode.window.showErrorMessage('Antigravity CLI (`agy`) was not found. Install/sign in to Antigravity CLI, then verify again.');return}const brief=await vscode.window.showInputBox({title:`New ${c.title}`,prompt:'Describe the video you want GraviStudio to produce',placeHolder:'Example: Create a 30-second 9:16 launch video using the real UI and no paid providers.'});if(!brief)return;const wf=vscode.workspace.workspaceFolders&&vscode.workspace.workspaceFolders[0];let root=wf?wf.uri.fsPath:null;if(!root){const p=await vscode.window.showOpenDialog({canSelectFolders:true,canSelectFiles:false,canSelectMany:false,openLabel:'Use as GraviStudio project folder'});if(!p||!p[0])return;root=p[0].fsPath}const stateDir=path.join(root,'.gravistudio');fs.mkdirSync(stateDir,{recursive:true});const checkpoint=path.join(stateDir,'checkpoint.json');const job={id:crypto.randomUUID(),category:c.id,title:c.title,brief,route:c.route,stage:'requirements',completedStages:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};fs.writeFileSync(checkpoint,JSON.stringify(job,null,2));const free=vscode.workspace.getConfiguration('gravistudio').get('freeMode',true);const modules=configPath('moduleDirectory','~/.gravistudio/modules');const prompt=[`You are running a GraviStudio video production job.`,`Category: ${c.title}. Preferred route: ${c.route}.`,`User brief: ${brief}`,`Project root: ${root}`,`Checkpoint: ${checkpoint}`,`Optional engine checkouts: ${modules}`,`Free Mode: ${free?'ON — do not use paid providers.':'OFF — request explicit approval before any paid provider.'}`,'Read the checkpoint and inspect project/assets first. Never redo a completed stage whose inputs are unchanged.','Use installed GraviStudio skills for requirements → storyboard → assets → composition → render → qc.','If assets are missing, use asset-agent and record provenance/license metadata.','Update .gravistudio/checkpoint.json after every completed stage. Do not claim success until output exists and video-qc passes.','Never use permission-bypass flags; stop at the exact checkpoint if permission is required.'].join('\n');const t=vscode.window.createTerminal({name:`GraviStudio · ${c.title}`,cwd:root});t.show(true);t.sendText(`${quote(agy)} -p ${quote(prompt)} --output-format stream-json`,true);vscode.window.showInformationMessage(`Started ${c.title}. Checkpoint created at .gravistudio/checkpoint.json.`)}
function quote(v){const s=String(v);return process.platform==='win32'?`"${s.replace(/`/g,'``').replace(/"/g,'`"')}"`:`'${s.replace(/'/g,`'\\''`)}'`}
module.exports={startJob};
