'use strict';
const vscode=require('vscode');
const fs=require('fs');
const path=require('path');
const os=require('os');
const {spawnSync}=require('child_process');
const {EXTERNAL,CATEGORIES}=require('./data');
let output;
function setOutput(o){output=o}
function log(s){if(output)output.appendLine(s)}
function expandHome(p){if(p==='~')return os.homedir();if(p.startsWith('~/')||p.startsWith('~\\'))return path.join(os.homedir(),p.slice(2));return p}
function configPath(key,fallback){return expandHome(String(vscode.workspace.getConfiguration('gravistudio').get(key,fallback)||fallback))}
function copyDir(src,dst){fs.mkdirSync(dst,{recursive:true});for(const e of fs.readdirSync(src,{withFileTypes:true})){const a=path.join(src,e.name),b=path.join(dst,e.name);e.isDirectory()?copyDir(a,b):fs.copyFileSync(a,b)}}
function run(cmd,args=[],opts={}){log(`[exec] ${cmd} ${args.join(' ')}`);const r=spawnSync(cmd,args,{cwd:opts.cwd,encoding:'utf8',shell:process.platform==='win32',timeout:opts.timeout||120000,windowsHide:true});if(r.stdout)output&&output.append(r.stdout);if(r.stderr)output&&output.append(r.stderr);return r}
function commandReady(c){const r=process.platform==='win32'?run('where',[c],{timeout:7000}):run('sh',['-lc',`command -v ${c}`],{timeout:7000});return r.status===0}
function findAgy(){if(commandReady('agy'))return'agy';const cs=process.platform==='win32'?[path.join(process.env.LOCALAPPDATA||'','agy','bin','agy.exe'),path.join(process.env.LOCALAPPDATA||'','agy','bin','agy.cmd')]:[path.join(os.homedir(),'.local','bin','agy')];return cs.find(p=>p&&fs.existsSync(p))||null}
function installBundledSkills(context){const src=path.join(context.extensionPath,'resources','plugin','skills');const dst=configPath('antigravitySkillsPath','~/.gemini/antigravity/skills');fs.mkdirSync(dst,{recursive:true});for(const name of fs.readdirSync(src)){const skill=path.join(src,name);if(!fs.statSync(skill).isDirectory())continue;copyDir(skill,path.join(dst,name));log(`[init] bundled ${name} -> ${path.join(dst,name)}`)}copyDir(path.join(context.extensionPath,'resources','plugin'),path.join(os.homedir(),'.gravistudio','plugin'))}
async function doctor(context){const skillRoot=configPath('antigravitySkillsPath','~/.gemini/antigravity/skills');const bundled=path.join(context.extensionPath,'resources','plugin','skills');const skills={};for(const n of fs.readdirSync(bundled)){if(fs.statSync(path.join(bundled,n)).isDirectory())skills[n]=fs.existsSync(path.join(skillRoot,n,'SKILL.md'))}const moduleRoot=configPath('moduleDirectory','~/.gravistudio/modules');const modules={};for(const id of Object.keys(EXTERNAL))modules[id]=fs.existsSync(path.join(moduleRoot,id));const state={version:'0.2.0',freeMode:vscode.workspace.getConfiguration('gravistudio').get('freeMode',true),skillsPath:skillRoot,modulePath:moduleRoot,runtime:{agy:Boolean(findAgy()),ffmpeg:commandReady('ffmpeg'),ffprobe:commandReady('ffprobe'),git:commandReady('git'),node:commandReady('node')},skills,modules,categories:CATEGORIES,checkedAt:new Date().toISOString()};log(`[doctor] ${JSON.stringify(state)}`);return state}
function discoverSkills(repoRoot,skillRoot,prefix){const hits=[];function walk(dir,d){if(d>5||hits.length>80)return;let es;try{es=fs.readdirSync(dir,{withFileTypes:true})}catch{return}if(es.some(e=>e.isFile()&&e.name==='SKILL.md'))hits.push(dir);for(const e of es)if(e.isDirectory()&&!['.git','node_modules'].includes(e.name))walk(path.join(dir,e.name),d+1)}walk(repoRoot,0);for(const src of hits){const base=path.basename(src).toLowerCase();const name=prefix==='brag'&&base==='brag'?'brag':`${prefix}-${base}`.replace(/[^a-z0-9-]/g,'-');copyDir(src,path.join(skillRoot,name));log(`[init] discovered ${name}`)}}
async function installModule(context,id,quiet=false){const mod=EXTERNAL[id];if(!mod)throw new Error(`Unknown module: ${id}`);if(!commandReady('git'))throw new Error('Git is required to install optional engines.');if(mod.experimental&&!quiet){const c=await vscode.window.showWarningMessage(`${mod.label} is experimental and may require a capable local GPU. Continue?`,{modal:true},'Install');if(c!=='Install')return}const root=configPath('moduleDirectory','~/.gravistudio/modules');fs.mkdirSync(root,{recursive:true});const dest=path.join(root,id);await vscode.window.withProgress({location:vscode.ProgressLocation.Notification,title:`GraviStudio: ${mod.label}`,cancellable:false},async p=>{if(fs.existsSync(path.join(dest,'.git'))){p.report({message:'Updating existing checkout…'});const r=run('git',['-C',dest,'pull','--ff-only'],{timeout:180000});if(r.status!==0)throw new Error(`Could not update ${mod.label}. See logs.`)}else{p.report({message:'Downloading repository…'});fs.rmSync(dest,{recursive:true,force:true});const r=run('git',['clone','--depth','1',mod.repo,dest],{timeout:600000});if(r.status!==0)throw new Error(`Could not download ${mod.label}. See logs.`)}if(id==='brag'||id==='hyperframes')discoverSkills(dest,configPath('antigravitySkillsPath','~/.gemini/antigravity/skills'),id)});if(!quiet)vscode.window.showInformationMessage(`${mod.label} installed under ${dest}.`)}
module.exports={setOutput,configPath,findAgy,installBundledSkills,doctor,installModule};
